#!/usr/bin/env bash
set -euo pipefail

repo_path="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
index_output="$(npx --yes codebase-memory-mcp cli index_repository "{\"repo_path\":\"$repo_path\"}")"
printf '%s\n' "$index_output"
project_name="$(printf '%s\n' "$index_output" | sed -n 's/.*"project":"\([^"]*\)".*/\1/p' | head -n 1)"
if [[ -z "$project_name" ]]; then
  echo "Could not determine the indexed project name." >&2
  exit 1
fi
{
  echo "# Codebase Memory Snapshot"
  echo
  echo 'Generated by `codebase-memory-mcp get_architecture`.'
  echo
  echo 'Do not edit this file manually; regenerate it with `scripts/update_codebase_memory.sh`.'
  echo
  npx --yes codebase-memory-mcp cli get_architecture "{\"project\":\"$project_name\",\"aspects\":[\"all\"]}"
} > "$repo_path/docs/CODEBASE_MEMORY.md"
